Comp2084-CarDealer/Models/AboutViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Comp2084_CarDealer.Models
{
    public class AboutViewModel
    {
        public String Title { get; set; }
        public String Message { get; set; }
        public String NewItem { get; set; }
    }
}

Comp2084-CarDealer/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Comp2084_CarDealer.Models;

namespace Comp2084_CarDealer.Controllers
{
    public class CarsController : Controller
    {

        ICarDAL DAL;
        public CarsController(ICarDAL DAL)
        {
            this.DAL = DAL;
        }

        [Route("cars/list")]
        // GET: Cars
        public ActionResult Index()
        {
            var cars = DAL.GetAllCars();
            return View(cars.ToList());
        }

        //[Route("cars/details/{name}")]
        //public String Details(String name)
        //{
        //    return "Car name: " + name;
        //}

        [Route("cars/details/{id:int=1}")]
        // GET: Cars/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = DAL.FindById(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        [Authorize(Roles ="Admin")]
        // GET: Cars/Create
        public ActionResult Create()
        {
            ViewBag.CarTypeId = new SelectList(DAL.GetCarTypes(), "id", "Name");
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]

        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Model,Make,Price,CarTypeId")] Car car)
        {
            if (ModelState.IsValid)
            {
                DAL.SaveNewCar(car);
                return RedirectToAction("Index");
            }

            ViewBag.CarTypeId = new SelectList(DAL.GetCarTypes(), "id", "Name", car.CarTypeId);
            return View(car);
        }

        // GET: Cars/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = DAL.FindById(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarTypeId = new SelectList(DAL.GetCarTypes(), "id", "Name", car.CarTypeId);
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Model,Make,Price,CarTypeId")] Car car)
        {
            if (ModelState.IsValid)
            {
                DAL.UpdateCar(car);
                return RedirectToAction("Index");
            }
            ViewBag.CarTypeId = new SelectList(DAL.GetCarTypes(), "id", "Name", car.CarTypeId);
            return View(car);
        }

        // GET: Cars/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = DAL.FindById(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DAL.DeleteCar(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                DAL.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Comp2084-CarDealer/Controllers/HomeController.cs
using Comp2084_CarDealer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Comp2084_CarDealer.Controllers
{
    [RequireHttps]
    [Route("home/{action=index}")]
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Route("")]
        [Route("home")]
        [Route("home/index")]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {

            AboutViewModel avm = new AboutViewModel()
            {
                Title = "About our car dealership",
                Message = "We are a world renowned car dealership with the finest vehicles.",
                NewItem = "This is our new Item variable!"
            };

            return View(avm);
        }


        public ActionResult Special()
        {
            var SaleCar = GetSpecial();
            return PartialView("_Special", SaleCar);
        }
        // Select an album and discount it by 50%        
        private Car GetSpecial()
        {
            var SaleCar = db.Cars
                .OrderBy(a => System.Guid.NewGuid())
                .First();
            SaleCar.Price *= 0.5m;
            return SaleCar;
        }

        public ActionResult CarSearch(string q)
        {
            var cars = GetCars(q);
            return PartialView(cars);
        }

        public ActionResult QuickSearch(string term)
        {
            var cars = GetCars(term).Select(a => new { value = a.Make +" "+a.Model });
            return Json(cars, JsonRequestBehavior.AllowGet);
        }


        private List<Car> GetCars(string searchString)
        {
            return db.Cars.Where(a => a.Model.Contains(searchString) || a.Make.Contains(searchString)).ToList();
        }

        [Route("testRoute/{day}/{year}/{month}")]
        public String testRoute(String day, String month, String year)
        {
            return "DAY: " + day + " Month: " + month + " year: " + year;
        }

        [Authorize]
        public ActionResult Support()
        {
            ViewBag.Message = "This is a support page, you can get help here if you need it!";
            return View();
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Comp2084-CarDealer/Views/Home/About.cshtml
@using Comp2084_CarDealer.Models
@model  AboutViewModel

@{
    ViewBag.Title = Model.Title;
}

<h2>@Model.Title.</h2>
<h3>@Model.Message</h3>
<h3>@Model.NewItem</h3>
  
<p>Use this area to provide additional information.</p>

Comp2084-CarDealer/Views/Home/CarSearch.cshtml
@model IEnumerable<Comp2084_CarDealer.Models.Car>

@{
    ViewBag.Title = "Search Results";
}

<h2>CarSearch</h2>


<table class="table">


@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Details", "Details","Cars", new { id = item.Id }, new { })
            @Html.DisplayFor(modelItem => item.TypeOfCar.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Make)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>

    </tr>
}

</table>

Comp2084-CarDealer/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Comp2084-CarDealer/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
    <div id="special">

    </div>
    <div>
        @Ajax.ActionLink("specials!",
                "special",
                null,
                new AjaxOptions
                {
                    UpdateTargetId = "special",
                    InsertionMode = InsertionMode.Replace,
                    HttpMethod = "GET"
                },
                new { @class = "btn btn-primary" })
    </div>

</div>

Comp2084-CarDealer/Views/Home/Support.cshtml
@{
    ViewBag.Title = "Support";
}

<h2>Support</h2>

<h3>@ViewBag.Message</h3>

@section Footer
{
 <p>This is our footer HTML Content</p>    
}

Comp2084-CarDealer/Views/Home/_Special.cshtml
@model Comp2084_CarDealer.Models.Car

@{
    ViewBag.Title = "_Special";
}

<h2>_Special</h2>

<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TypeOfCar.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeOfCar.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Make)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Make)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>